version: "3.9"

services:
  frontend:
    build: ./frontend
    volumes:
      - frontend-build:/app/Frontend/build

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - frontend-build:/app/Frontend/build  
    depends_on:
      - frontend

volumes:
  frontend-build: