describe('Caja negra -> Registro', () => {
    it('Entrar a registro desde login', () => {
      cy.visit('http://127.0.0.1:8000/home')
      cy.get('#login').click()
      cy.get('#registro').click()
    })
    it('Registro error [Cedula repetida]', () => {
      cy.visit('http://127.0.0.1:8000/home')
      cy.get('#login').click()
      cy.get('#registro').click()
      cy.get('#tipo_documento').click()
      cy.get('.MuiList-root > [tabindex="0"]').click()
      cy.get('#cedula').type('1006756545')
      cy.get('#nombre').type('Anabela')
      cy.get('#email').type('anabela@gmail.com')
      cy.get('#contrasena').type('1111')
      cy.get('#contrasena_re').type('1111')
      cy.get('#telefono').type('3134448282')
      cy.get('#ciudad').type('Bogota')
      cy.get('#direccion').type('Cl. 23 #17d-103')
      cy.get('#registrarse').click()
      cy.get('.swal-text').contains('Ya existe una cuenta asociada a esta cédula')
    })
    it('Registro error [Contraseñas no coinciden]', () => {
      cy.visit('http://127.0.0.1:8000/home')
      cy.get('#login').click()
      cy.get('#registro').click()
      cy.get('#tipo_documento').click()
      cy.get('.MuiList-root > [tabindex="0"]').click()
      cy.get('#cedula').type('1005969061')
      cy.get('#nombre').type('Juan Diego')
      cy.get('#email').type('juan.diego.arias@correounivalle.edu.co')
      cy.get('#contrasena').type('1111')
      cy.get('#contrasena_re').type('1112131')
      cy.get('#telefono').type('3134448282')
      cy.get('#ciudad').type('Cali')
      cy.get('#direccion').type('Cl. 23 #17d-103')
      cy.get('#registrarse').click()
      cy.get('.swal-text').contains('Las contraseñas no coinciden')
    })
    it('Registro error [Correo ya en uso]', () => {
      cy.visit('http://127.0.0.1:8000/home')
      cy.get('#login').click()
      cy.get('#registro').click()
      cy.get('#tipo_documento').click()
      cy.get('.MuiList-root > [tabindex="0"]').click()
      cy.get('#cedula').type('1005969061')
      cy.get('#nombre').type('Juan Diego')
      cy.get('#email').type('ana@gmail.com')
      cy.get('#contrasena').type('1111')
      cy.get('#contrasena_re').type('1111')
      cy.get('#telefono').type('3134448282')
      cy.get('#ciudad').type('Cali')
      cy.get('#direccion').type('Cl. 23 #17d-103')
      cy.get('#registrarse').click()
      cy.get('.swal-text').contains('Este correo electrónico ya está en uso')
    })
    it('Registro error [Contraseña muy corta]', () => {
      cy.visit('http://127.0.0.1:8000/home')
      cy.get('#login').click()
      cy.get('#registro').click()
      cy.get('#tipo_documento').click()
      cy.get('.MuiList-root > [tabindex="0"]').click()
      cy.get('#cedula').type('1005969061')
      cy.get('#nombre').type('Juan Diego')
      cy.get('#email').type('juan.diego.arias@correounivalle.edu.co')
      cy.get('#contrasena').type('111')
      cy.get('#contrasena_re').type('111')
      cy.get('#telefono').type('3134448282')
      cy.get('#ciudad').type('Cali')
      cy.get('#direccion').type('Cl. 23 #17d-103')
      cy.get('#registrarse').click()
      cy.get('.swal-text').contains('La contraseña es muy corta')
    })
  })
  