# Generated by Django 4.1.2 on 2023-03-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa_mes', models.DateField(primary_key=True, serialize=False)),
                ('tarifa_mes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estrato1', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estrato2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estrato3', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estrato4', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estrato5', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estrato6', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comercial_industrial', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'tarifa',
                'managed': False,
            },
        ),
    ]
