# Generated by Django 4.1.2 on 2023-04-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0002_tarifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('ano_publicacion', models.CharField(max_length=100)),
                ('numero_paginas', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('venta', models.CharField(max_length=100)),
                ('renta', models.CharField(max_length=100)),
                ('intercambio', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_renta', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transaccion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'transaccion',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Bancoaliado',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Inmueble',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Publicidad',
        ),
        migrations.DeleteModel(
            name='Tarifa',
        ),
        migrations.DeleteModel(
            name='Tipousuario',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
