# Generated by Django 4.1.4 on 2023-05-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0003_libro_transaccion_delete_bancoaliado_delete_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercambiosAvisos',
            fields=[
                ('id_aviso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'intercambiosavisos',
                'managed': False,
            },
        ),
    ]
